### ISSUE TITLE
Migration database

### ISSUE THREAD

**Issue by phienngo** [mrcoco/slim3-eloquent-skeleton#5]
Hi all,
I just run this project, but the step 3 ( $ vendor/davedevelopment/phpmig/bin/phpmig migrate) not working for me.

I goto vendor\davedevelopment\phpmig\bin and then run $ phpmig  migrate.
But the result is 

  [InvalidArgumentException]
  The file "phpmig.php" does not exist (in: C:\xampp\htdocs\my-app\vendor\dav
  edevelopment\phpmig\bin\config, C:\xampp\htdocs\my-app\vendor\davedevelopme
  nt\phpmig\bin).

migrate [-s|--set SET] [-b|--bootstrap BOOTSTRAP] [-t|--target TARGET]

Please help me fix this issue to RUN the project.
Thanks.

**Comment by mrcoco** [comment]
maybe you need to change the version phpmig on composer.json "davedevelopment/phpmig": "1.2",

**Comment by phienngo** [comment]
At now, this has version 1.2.
"davedevelopment/phpmig": "^1.2",

Do you have any way to run this project now ?

**Comment by mrcoco** [comment]
may you try php cli.php migrate

**Comment by phienngo** [comment]
That is working fine for me. Thanks you so much.
