### ISSUE TITLE
Routes not found in Apache server Ubuntu PC

### ISSUE THREAD

**Issue by phienngo** [mrcoco/slim3-eloquent-skeleton#6]
Hi all,
When deploy this project to Xampp on Windows, all working fine.
But deploy to Apache on Ubuntu PC , only public/index.php working. Any else routes (ex: /login) is not working.

I don't know missing config something.

Do you have any idea for this issue.
Thanks,

**Comment by mrcoco** [comment]
any error message??

**Comment by phienngo** [comment]
Ok thanks sir. I just config my apache. It's running now.
